language: objective-c 

# macOS and Xcode Version
os: osx
osx_image: xcode11.5

# Build dependencies with verbose logging to avoid Travis timing out.
install:
  - ./fetchDependencies -v --macos

script:
  - xcodebuild build -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package (macOS only)"
  - xcodebuild build -workspace Demos/Demos.xcworkspace -scheme "Cube-macOS"

